name: C++ CI Workflow

# Define when the workflow should be triggered
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define jobs to be run
jobs:
  build:
    # Specify the environment
    runs-on: ubuntu-latest

    # Define steps
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (if any)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      # Compile the C++ code
      - name: Build
        run: |
          mkdir -p build
          g++ -o build/my_app src/main.cpp

      # Run tests (assuming there is a `tests` folder)
      - name: Run tests
        run: |
          for test_file in tests/*.cpp; do
            g++ -o build/test_app "$test_file"
            ./build/test_app
          done

      # Optionally, deploy or upload artifacts
      - name: Upload artifact (optional)
        if: always() # Upload even if a step fails
        uses: actions/upload-artifact@v3
        with:
          name: my_app
          path: build/my_app
